[[redirects]]
  from = "/api/*"
  to = "https://haucommit.com/:splat"
  force = true 
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"